import argparse
import json
from pathlib import Path

try:
    from tests.tooling.threshold_policy import DEFAULT_COVERAGE_THRESHOLD, get_coverage_threshold, is_valid_threshold
except ModuleNotFoundError:
    from threshold_policy import DEFAULT_COVERAGE_THRESHOLD, get_coverage_threshold, is_valid_threshold


def parse_args(argv=None) -> argparse.Namespace:
    def threshold_type(value: str) -> float:
        parsed = float(value)
        if not is_valid_threshold(parsed):
            raise argparse.ArgumentTypeError("threshold must be a finite value between 0 and 100")
        return parsed

    parser = argparse.ArgumentParser(description="Enforce strict per-file coverage threshold from coverage.json.")
    parser.add_argument("coverage_json", type=Path, help="Path to coverage JSON report generated by coverage.py")
    parser.add_argument(
        "--threshold",
        type=threshold_type,
        default=get_coverage_threshold(),
        help=(
            f"Minimum threshold (files must be at or above this value). Default: {DEFAULT_COVERAGE_THRESHOLD:.1f} (or $COVERAGE_THRESHOLD)"
        ),
    )
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)

    if not args.coverage_json.exists():
        print(f"ERROR: Coverage report not found: {args.coverage_json}")
        return 2

    with args.coverage_json.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    files = payload.get("files", {})
    failing = []
    measured_production_files = 0

    for filename, details in files.items():
        filename_normalized = filename.replace("\\", "/")
        path_parts = filename_normalized.split("/")
        if "tests" in path_parts:
            continue

        summary = details.get("summary", {})
        percent = float(summary.get("percent_covered", 0.0))
        statements = int(summary.get("num_statements", 0))

        if statements == 0:
            continue

        measured_production_files += 1

        if percent < args.threshold:
            failing.append((filename_normalized, percent))

    if measured_production_files == 0:
        print("FAIL: No measured production files found in coverage report")
        return 1

    if failing:
        print(f"FAIL: Per-file coverage must be >= {args.threshold:.2f}%")
        for path, percent in sorted(failing):
            print(f"  - {path}: {percent:.2f}%")
        return 1

    print(f"PASS: All measured files are >= {args.threshold:.2f}% coverage")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
